// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sas.BodyDatabase.Database;

#nullable disable

namespace Sas.BodyDatabase.Migrations
{
    [DbContext(typeof(BodyContext))]
    [Migration("20220104225937_InitalCrate")]
    partial class InitalCrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sas.Database.Entities.BodyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<int>("VelocityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("VelocityId");

                    b.ToTable("Bodies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mass = 1000.0,
                            Name = "body1",
                            PositionId = 1,
                            Radius = 5.0,
                            VelocityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Mass = 1000.0,
                            Name = "body2",
                            PositionId = 2,
                            Radius = 5.0,
                            VelocityId = 2
                        });
                });

            modelBuilder.Entity("Sas.Database.Entities.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            X = 10.0,
                            Y = 0.0,
                            Z = 0.0
                        },
                        new
                        {
                            Id = 2,
                            X = -10.0,
                            Y = 0.0,
                            Z = 0.0
                        });
                });

            modelBuilder.Entity("Sas.Database.Entities.VelocityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Velocities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            X = 0.0,
                            Y = 10.0,
                            Z = 0.0
                        },
                        new
                        {
                            Id = 2,
                            X = 0.0,
                            Y = -10.0,
                            Z = 0.0
                        });
                });

            modelBuilder.Entity("Sas.Database.Entities.BodyEntity", b =>
                {
                    b.HasOne("Sas.Database.Entities.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sas.Database.Entities.VelocityEntity", "Velocity")
                        .WithMany()
                        .HasForeignKey("VelocityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Velocity");
                });
#pragma warning restore 612, 618
        }
    }
}
